import turtle
turtle.color('red')
turtle.bgcolor('black')
turtle.left(90)
turtle.pensize(8)
turtle.forward(100)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.left(135)
turtle.forward(70)
